clc
clear
% function main_RNN(Ep, Numcell)
Ep = 5;
Numcell = 1;

load RNN_training_data_input_size_200

idx = randperm(size(XTrain,1),160000/4);
XValidation = XTrain(idx,1);
XTrain(idx,:) = [];
YValidation = YTrain(idx,1);
YTrain(idx,:) = [];

YValidation = categorical(YValidation,[1 0],{'ON','OFF'});
YTrain = categorical(YTrain,[1 0],{'ON','OFF'});

warning off parallel:gpu:device:DeviceLibsNeedsRecompiling
try
    gpuArray.eye(2)^2;
catch ME
end
try
    nnet.internal.cnngpu.reluForward(1);
catch ME
end

layers = [ ...
    sequenceInputLayer(1) % scalar
        
    lstmLayer(Numcell,'OutputMode','last')
    fullyConnectedLayer(2)
    softmaxLayer
    classificationLayer
    ];

options = trainingOptions('adam', ...
    'LearnRateSchedule','none', ...
    'LearnRateDropFactor',0.1, ...
    'LearnRateDropPeriod',1, ...
    'ExecutionEnvironment','cpu',...
    'InitialLearnRate',0.01, ...
    'shuffle','every-epoch', ...
    'MaxEpochs',Ep, ...
    'MiniBatchSize', 100, ...
    'ValidationData', {XValidation, YValidation}, ...
    'ValidationFrequency', 500, ...
    'plots','training-progress', ...
    'Verbose',false);

% options = trainingOptions('adam', ...
%     'ExecutionEnvironment','auto',...
%     'InitialLearnRate',0.001, ...
%     'shuffle','every-epoch', ...
%     'MaxEpochs',Ep, ...
%     'MiniBatchSize', 32, ...
%     'ValidationData', {XValidation, YValidation}, ...
%     'ValidationFrequency', 500, ...
%     'plots','training-progress', ...
%     'Verbose',false);

[net, info] = trainNetwork(XTrain,YTrain,layers,options);

% SS = sprintf('./network/never_batch100_net_adam_Ep_%d_001_LSTMcell_%d', Ep, Numcell);
% save(SS, 'net', 'info');


%     'LearnRateDropFactor',0.9, ...
%     'LearnRateDropPeriod',1, ...
%     'InitialLearnRate',0.001, ...